FROM ubuntu:latest

# ENTRYPOINT é comando fixo
ENTRYPOINT [ "echo", "Hello" ]
# Esta servindo como parametro para o ENTRYPOINT,
# O CMD é substituido quando chamamos o
# docker run --rm matheusmaicagoos/hello [parametro]
CMD ["World"]
